-- 1. Criar o banco de dados
-- CREATE DATABASE IF NOT EXISTS extensao
-- CHARACTER SET utf8mb4
-- COLLATE utf8mb4_unicode_ci;

-- 2. Usar o banco de dados
USE extensao;

INSERT INTO Customer (id, name, cpf, phone, email, address, status, createdAt, updatedAt) VALUES
                                                                                              ('cuid1', 'Maria Silva Eventos', '12345678901', '69988887777', 'maria@eventos.com', 'Av. Principal, 123', 'active', NOW(), NOW()),
                                                                                              ('cuid2', 'João Santos Produções', '98765432101', '69999995555', 'joao@producoes.com', 'Rua das Flores, 456', 'active', NOW(), NOW()),
                                                                                              ('cuid3', 'Ana Paula Festas', '45678912301', '69977773333', 'ana@festas.com', 'Rua do Comércio, 789', 'active', NOW(), NOW());


INSERT INTO Event (
    name, description, event_date, location, max_capacity, status, event_type,
    created_at, updated_at, duration, rent, clientId
) VALUES (
             'Aniversário de 30 anos',
             'Festa de aniversário de 30 anos',
             '2025-01-01 00:00:00',
             'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO',
             150, 'scheduled', 'aniversario',
             NOW(), NOW(),
             6.0, 500.00, 'cuid1'
         );

-- Eventos 2025
INSERT INTO Event (name, description, event_date, location, max_capacity, status, event_type, created_at, updated_at, duration, rent, clientId) VALUES
                                                                                                                                                    ('Aniversário de 30 anos', 'Festa de aniversário de 30 anos', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 150, 'scheduled', 'aniversario', NOW(), NOW(), 6.0, 500.00, 'cuid1'),
                                                                                                                                                    ('Casamento João e Maria', 'Cerimônia e recepção de casamento', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 200, 'completed', 'casamento', NOW(), NOW(), 4.5, 150.00, 'cuid2'),
                                                                                                                                                    ('Churrasco de Confraternização', 'Churrasco com amigos e familiares', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 1000, 'scheduled', 'churrasco', NOW(), NOW(), 5.0, 700.00, 'cuid3'),
                                                                                                                                                    ('Aniversário Infantil', 'Festa de aniversário para crianças', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 400, 'completed', 'aniversario', NOW(), NOW(), 6.0, 380.00, 'cuid1'),
                                                                                                                                                    ('Casamento Pedro e Ana', 'Celebração de casamento tradicional', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 300, 'scheduled', 'casamento', NOW(), NOW(), 3.5, 250.00, 'cuid2'),
                                                                                                                                                    ('Churrasco de Aniversário', 'Churrasco para comemorar aniversário', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 500, 'scheduled', 'churrasco', NOW(), NOW(), 4.0, 400.00, 'cuid3'),
                                                                                                                                                    ('Aniversário de 50 anos', 'Festa de aniversário de meio século', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 200, 'completed', 'aniversario', NOW(), NOW(), 3.0, 180.00, 'cuid1'),
                                                                                                                                                    ('Casamento Civil', 'Cerimônia íntima de casamento', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 350, 'scheduled', 'casamento', NOW(), NOW(), 5.0, 300.00, 'cuid2'),
                                                                                                                                                    ('Churrasco de Família', 'Reunião familiar com churrasco', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 600, 'scheduled', 'churrasco', NOW(), NOW(), 6.0, 350.00, 'cuid3'),
                                                                                                                                                    ('Aniversário de 1 ano', 'Festa de primeiro aniversário', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 250, 'completed', 'aniversario', NOW(), NOW(), 3.0, 200.00, 'cuid1'),
                                                                                                                                                    ('Casamento Religioso', 'Cerimônia na igreja e recepção', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 150, 'scheduled', 'casamento', NOW(), NOW(), 4.0, 450.00, 'cuid2'),
                                                                                                                                                    ('Churrasco de Empresa', 'Evento corporativo com churrasco', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 400, 'scheduled', 'churrasco', NOW(), NOW(), 6.0, 300.00, 'cuid3'),
                                                                                                                                                    ('Aniversário de 15 anos', 'Festa de debutante', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 300, 'scheduled', 'aniversario', NOW(), NOW(), 4.5, 250.00, 'cuid1'),
                                                                                                                                                    ('Casamento na Praia', 'Cerimônia à beira-mar', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 200, 'scheduled', 'casamento', NOW(), NOW(), 4.0, 280.00, 'cuid2'),
                                                                                                                                                    ('Churrasco de Sábado', 'Encontro descontraído no final de semana', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 350, 'scheduled', 'churrasco', NOW(), NOW(), 5.0, 300.00, 'cuid3'),
                                                                                                                                                    ('Aniversário Surpresa', 'Festa surpresa para aniversariante', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 120, 'scheduled', 'aniversario', NOW(), NOW(), 8.0, 500.00, 'cuid1'),
                                                                                                                                                    ('Casamento VIP', 'Evento de casamento luxuoso', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 400, 'scheduled', 'casamento', NOW(), NOW(), 6.0, 350.00, 'cuid2'),
                                                                                                                                                    ('Churrasco Beneficente', 'Evento para arrecadar fundos', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 300, 'scheduled', 'churrasco', NOW(), NOW(), 5.0, 280.00, 'cuid3'),
                                                                                                                                                    ('Aniversário de Casamento', 'Celebração de bodas', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 100, 'completed', 'aniversario', NOW(), NOW(), 3.0, 150.00, 'cuid1'),
                                                                                                                                                    ('Casamento Rústico', 'Celebração em fazenda', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 800, 'scheduled', 'casamento', NOW(), NOW(), 7.0, 600.00, 'cuid1'),
                                                                                                                                                    ('Churrasco de Domingo', 'Evento casual no domingo', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 1000, 'scheduled', 'churrasco', NOW(), NOW(), 8.0, 450.00, 'cuid2'),
                                                                                                                                                    ('Aniversário de 18 anos', 'Festa de maioridade', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 200, 'scheduled', 'aniversario', NOW(), NOW(), 5.0, 400.00, 'cuid3'),
                                                                                                                                                    ('Casamento Temático', 'Celebração com tema medieval', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 500, 'scheduled', 'casamento', NOW(), NOW(), 4.0, 250.00, 'cuid1'),
                                                                                                                                                    ('Churrasco de Verão', 'Evento sazonal ao ar livre', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 600, 'scheduled', 'churrasco', NOW(), NOW(), 5.5, 350.00, 'cuid2');


-- Eventos 2024
INSERT INTO Event (name, description, event_date, location, max_capacity, status, event_type, created_at, updated_at, duration, rent, clientId) VALUES
                                                                                                                                                    ('Aniversário Corporativo', 'Festa de aniversário da empresa', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 300, 'scheduled', 'aniversario', NOW(), NOW(), 6.5, 600.00, 'cuid2'),
                                                                                                                                                    ('Casamento de Verão', 'Cerimônia de casamento ao ar livre', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 120, 'ongoing', 'casamento', NOW(), NOW(), 12.0, 200.00, 'cuid3'),
                                                                                                                                                    ('Churrasco de Carnaval', 'Festa pré-carnaval com churrasco', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 500, 'completed', 'churrasco', NOW(), NOW(), 5.0, 350.00, 'cuid1'),
                                                                                                                                                    ('Aniversário de 25 anos', 'Festa de comemoração de bodas de prata', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 250, 'scheduled', 'aniversario', NOW(), NOW(), 4.0, 180.00, 'cuid2'),
                                                                                                                                                    ('Casamento de Páscoa', 'Celebração de casamento na época pascal', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 200, 'scheduled', 'casamento', NOW(), NOW(), 3.5, 150.00, 'cuid3'),
                                                                                                                                                    ('Churrasco Literário', 'Encontro de escritores com churrasco', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 300, 'scheduled', 'churrasco', NOW(), NOW(), 6.0, 280.00, 'cuid1'),
                                                                                                                                                    ('Aniversário da Mãe', 'Festa surpresa para o dia das mães', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 350, 'completed', 'aniversario', NOW(), NOW(), 5.5, 260.00, 'cuid2'),
                                                                                                                                                    ('Casamento Junino', 'Festa de casamento com tema junino', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 500, 'scheduled', 'casamento', NOW(), NOW(), 6.0, 400.00, 'cuid3'),
                                                                                                                                                    ('Churrasco de Férias', 'Reunião de férias com churrasco', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 250, 'scheduled', 'churrasco', NOW(), NOW(), 4.0, 200.00, 'cuid1'),
                                                                                                                                                    ('Aniversário do Pai', 'Festa em homenagem ao dia dos pais', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 300, 'scheduled', 'aniversario', NOW(), NOW(), 6.0, 350.00, 'cuid2'),
                                                                                                                                                    ('Casamento da Juventude', 'Celebração de casamento jovem', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 400, 'scheduled', 'casamento', NOW(), NOW(), 5.0, 320.00, 'cuid3'),
                                                                                                                                                    ('Churrasco Cultural', 'Evento cultural com churrasco', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 200, 'scheduled', 'churrasco', NOW(), NOW(), 3.0, 180.00, 'cuid1'),
                                                                                                                                                    ('Aniversário de Empresa', 'Comemoração de aniversário corporativo', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 150, 'scheduled', 'aniversario', NOW(), NOW(), 4.0, 250.00, 'cuid2'),
                                                                                                                                                    ('Casamento Temático', 'Casamento com tema regional', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 450, 'scheduled', 'casamento', NOW(), NOW(), 6.0, 300.00, 'cuid3'),
                                                                                                                                                    ('Churrasco de Natal', 'Confratenização natalina', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 200, 'scheduled', 'churrasco', NOW(), NOW(), 4.5, 160.00, 'cuid1'),
                                                                                                                                                    ('Aniversário de Final de Ano', 'Festa de réveillon e aniversário', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 500, 'scheduled', 'aniversario', NOW(), NOW(), 5.0, 500.00, 'cuid2'),
                                                                                                                                                    ('Casamento de Inverno', 'Celebração de casamento na estação', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 350, 'completed', 'casamento', NOW(), NOW(), 4.0, 220.00, 'cuid3'),
                                                                                                                                                    ('Churrasco de Cinema', 'Evento para cineastas', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 100, 'scheduled', 'churrasco', NOW(), NOW(), 3.5, 140.00, 'cuid1'),
                                                                                                                                                    ('Aniversário de Educação', 'Celebração de aniversário escolar', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 250, 'scheduled', 'aniversario', NOW(), NOW(), 5.0, 280.00, 'cuid2'),
                                                                                                                                                    ('Churrasco Ecológico', 'Evento sustentável com churrasco', NOW(), 'R. Nicarágua, 1226 - Nova Porto Velho, Porto Velho - RO', 300, 'scheduled', 'churrasco', NOW(), NOW(), 6.0, 300.00, 'cuid3');

